"""tên_thay_đổi

Revision ID: cb4fc39b88a4
Revises: 3d96de33ba13
Create Date: 2026-06-11 11:39:09.300683

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb4fc39b88a4'
down_revision: Union[str, None] = '3d96de33ba13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller', sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True))
    op.alter_column('seller', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.add_column('shipment', sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('shipment', sa.Column('seller_id', sa.Uuid(), nullable=False))
    op.add_column('shipment', sa.Column('delivery_partner_id', sa.Uuid(), nullable=False))
    op.alter_column('shipment', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.create_foreign_key(None, 'shipment', 'delivery_partner', ['delivery_partner_id'], ['id'])
    op.create_foreign_key(None, 'shipment', 'seller', ['seller_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shipment', type_='foreignkey')
    op.drop_constraint(None, 'shipment', type_='foreignkey')
    op.alter_column('shipment', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('shipment', 'delivery_partner_id')
    op.drop_column('shipment', 'seller_id')
    op.drop_column('shipment', 'created_at')
    op.alter_column('seller', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('seller', 'created_at')
    # ### end Alembic commands ###
